orbs:
  node: circleci/node@4.1.0

version: 2.1

commands:
  install-python2:
    description: "Install Python Version 2.7"
    steps:
      - run: sudo apt update
      - run: sudo apt upgrade
      - run: sudo apt install python2.7
      - run: sudo ln -s /usr/bin/python2.7 /usr/bin/python2 && sudo ln -s /usr/bin/python2 /usr/bin/python

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 15.7.0
          npm-version: 7.4.3
          yarn-version: 1.22.11
      - install-python2
      - node/install-packages:
          cache-path: ~/project/node_modules
          pkg-manager: yarn
          override-ci-command: 'yarn install --frozen-lockfile'
      - run:
          name: Generate Static File
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy_to_firebase:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - attach_workspace:
          at: .
      - checkout
      - node/install:
          install-yarn: true
          node-version: 15.7.0
          npm-version: 7.4.3
          yarn-version: 1.22.11
      - run:
          name: Firebase Deploy
          command: node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_to_firebase:
          requires:
            - build
