orbs:
  node: circleci/node@4.1.0

version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          cache-path: ~/project/node_modules
          pkg-manager: yarn
      - run:
          name: Generate Static File
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy_to_firebase:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          name: Check Dir
          command: ls
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_to_firebase:
          requires:
            - build
